# Ex - GroupBy

### Introduction:

GroupBy can be summarized as Split-Apply-Combine.

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Check out this [Diagram](http://i.imgur.com/yjNkiwL.png)  
### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv")

### Step 3. Assign it to a variable called drinks.

In [3]:
drinks = data

In [5]:
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF

### Step 4. Which continent drinks more beer on average?

In [10]:
drinks.groupby("continent")["beer_servings"].mean().sort_values(ascending = False).head(1)

continent
EU    193.777778
Name: beer_servings, dtype: float64

In [14]:
drinks.groupby("continent")["beer_servings"].mean().sort_values(ascending = False).head(1).index[0]

'EU'

### Step 5. For each continent print the statistics for wine consumption.

In [17]:
drinks.groupby("continent")["wine_servings"].describe()

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

### Step 6. Print the mean alcohol consumption per continent for every column

In [19]:
drinks.groupby("continent")[["total_litres_of_pure_alcohol","beer_servings","spirit_servings","wine_servings"]].mean()

,total_litres_of_pure_alcohol,beer_servings,spirit_servings,wine_servings
continent,,,,
AF,3.007547,61.471698,16.339623,16.264151
AS,2.170455,37.045455,60.840909,9.068182
EU,8.617778,193.777778,132.555556,142.222222
OC,3.381250,89.687500,58.437500,35.625000
SA,6.308333,175.083333,114.750000,62.416667

### Step 7. Print the median alcohol consumption per continent for every column

In [20]:
drinks.groupby("continent")[["total_litres_of_pure_alcohol","beer_servings","spirit_servings","wine_servings"]].median()

,total_litres_of_pure_alcohol,beer_servings,spirit_servings,wine_servings
continent,,,,
AF,2.30,32.0,3.0,2.0
AS,1.20,17.5,16.0,1.0
EU,10.00,219.0,122.0,128.0
OC,1.75,52.5,37.0,8.5
SA,6.85,162.5,108.5,12.0

### Step 8. Print the mean, min and max values for spirit consumption.
#### This time output a DataFrame

In [27]:
drinks[['spirit_servings']].agg(['mean', 'min', 'max'])

      spirit_servings
mean        80.994819
min          0.000000
max        438.000000

In [26]:

drinks.groupby("continent")["spirit_servings"].agg(['mean','min','max'])

                 mean  min  max
continent
AF          16.339623    0  152
AS          60.840909    0  326
EU         132.555556    0  373
OC          58.437500    0  254
SA         114.750000   25  302