# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv')

### Step 3. Assign it to a variable called baby_names.

In [3]:
baby_names = df

### Step 4. See the first 10 entries

In [4]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [5]:
baby_names.drop(['Unnamed: 0', 'Id'], axis=1, inplace=True)

In [6]:
baby_names.head()

      Name  Year Gender State  Count
0     Emma  2004      F    AK     62
1  Madison  2004      F    AK     48
2   Hannah  2004      F    AK     46
3    Grace  2004      F    AK     44
4    Emily  2004      F    AK     41

In [8]:
baby_names.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1016395 entries, 0 to 1016394
Data columns (total 5 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   Name    1016395 non-null  object
 1   Year    1016395 non-null  int64
 2   Gender  1016395 non-null  object
 3   State   1016395 non-null  object
 4   Count   1016395 non-null  int64
dtypes: int64(2), object(3)
memory usage: 38.8+ MB

In [9]:
baby_names.shape

(1016395, 5)

### Step 6. Is there more male or female names in the dataset?

In [7]:
baby_names['Gender'].value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

In [14]:
baby_names.groupby('Gender')["Name"].count()

Gender
F    558846
M    457549
Name: Name, dtype: int64

### Step 7. Group the dataset by name and assign to names

In [15]:
baby_names.groupby('Name').sum()

,Year,Gender,State,Count
Name,,,,
Aaban,4027,MM,NYNY,12
Aadan,8039,MMMM,CACACATX,23
Aadarsh,2009,M,IL,5
Aaden,393963,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...,ALALALALALALALARARARAZAZAZAZAZAZCACACACACACACA...,3426
Aadhav,2014,M,CA,6
...,...,...,...,...
Zyra,14085,FFFFFFF,CACACAFLTXTXTX,42
Zyrah,4024,FF,CATX,11
Zyren,2013,M,TX,6
Zyria,20089,FFFFFFFFFF,GAGAGALALALATXTXTXTX,59
Zyriah,18087,FFFFFFFFF,GAGALATXTXTXTXTXTX,58

### Step 8. How many different names exist in the dataset?

In [17]:
baby_names['Name'].nunique()

17632

### Step 9. What is the name with most occurrences?

In [18]:
baby_names.groupby('Name')["Count"].sum().sort_values(ascending=False).head(1)

Name
Jacob    242874
Name: Count, dtype: int64

### Step 10. How many different names have the least occurrences?

In [24]:
min_count = baby_names.groupby('Name')["Count"].sum().min()
min_count

5

In [25]:
count = (baby_names.groupby('Name')["Count"].sum() == min_count).sum()
count

np.int64(2578)

### Step 11. What is the median name occurrence?

In [26]:
median_count = baby_names.groupby('Name')["Count"].sum().median()
median_count

49.0

### Step 12. What is the standard deviation of names?

In [27]:
std_count = baby_names.groupby('Name')["Count"].sum().std()
std_count

11006.069467891111

### Step 13. Get a summary with the mean, min, max, std and quartiles.

In [28]:
baby_names.describe()

               Year         Count
count  1.016395e+06  1.016395e+06
mean   2.009053e+03  3.485012e+01
std    3.138293e+00  9.739735e+01
min    2.004000e+03  5.000000e+00
25%    2.006000e+03  7.000000e+00
50%    2.009000e+03  1.100000e+01
75%    2.012000e+03  2.600000e+01
max    2.014000e+03  4.167000e+03